# Generated by Django 4.1.7 on 2023-03-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50, verbose_name='imie')),
                ('nazwisko', models.CharField(max_length=50, verbose_name='nazwisko')),
                ('poczatkowy_stan_licznika', models.IntegerField(verbose_name='poczatkowy stan licznika')),
                ('godzina_wyjazdu', models.CharField(max_length=50, verbose_name='godzina wyjazdu')),
                ('data_wyjazdu', models.CharField(max_length=50, verbose_name='data wyjazdu')),
                ('trasa', models.CharField(max_length=50, verbose_name='trasa')),
                ('koncowy_stan_licznika', models.IntegerField(verbose_name='koncowy stan licznika')),
                ('uwagi_kierowcy', models.CharField(max_length=50, verbose_name='uwagi')),
                ('dlugosc_trasy', models.IntegerField(verbose_name='dlugosc trasy')),
            ],
        ),
    ]
